=== darpandeb/WSD-LAB_2247213/WSD_CAT_1_2247213/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="company">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="employee" minOccurs="1" maxOccurs="5"> 
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="empid" type="xs:integer"/>
                        <xs:element name="empname" type="xs:string"/>
                        <xs:element name="empage" type="xs:integer"/>  
                        <xs:element name="empsalary">
                          <xs:simpleType>
                                 <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="50000" />
                                    <xs:maxInclusive value="200000" />
                              </xs:restriction>
                        </xs:simpleType>
                      </xs:element>
                        <xs:element name="empmail" type="xs:string"/>
                        <xs:element name="empphn" type="xs:integer"/>
                        <xs:element name="empdesg" type="xs:string"/>
                        <xs:element name="promo" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>  
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== darpandeb/WSD-LAB_2247213/WSD_CAT_1_2247213/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>


<company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee>
        <empid>1</empid>
        <empname>Raj</empname>
        <empage>45</empage>
        <empsalary>51000</empsalary>
        <empmail>dsdj@jdsbdjbsj.com</empmail>
        <empphn>1213124354</empphn>
        <empdesg>Freshie</empdesg>
        <promo>dsdsd</promo>
    </employee>
    <employee>
        <empid>2</empid>
        <empname>Amit</empname>
        <empage>50</empage>
        <empsalary>35000</empsalary>
        <empmail>dsdj@jdsbdjbsj.com</empmail>
        <empphn>1213124354</empphn>
        <empdesg>Experienced</empdesg>
        <promo>dsdsd</promo>
    </employee>
    <employee>
        <empid>3</empid>
        <empname>Mou</empname>
        <empage>59</empage>
        <empsalary>75000</empsalary>
        <empmail>dsdj@jdsbdjbsj.com</empmail>
        <empphn>1213124354</empphn>
        <empdesg>Experienced</empdesg>
        <promo>dsdsd</promo>
    </employee>
    <employee>
        <empid>4</empid>
        <empname>Nandini</empname>
        <empage>35</empage>
        <empsalary>65000</empsalary>
        <empmail>dsdj@jdsbdjbsj.com</empmail>
        <empphn>1213124354</empphn>
        <empdesg>Freshie</empdesg>
        <promo>dsdsd</promo>
    </employee>
</company>
